services:
  catalogdb:
    image: postgres:17
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    container_name: Catalog.API
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.Api/Dockerfile

volumes:
  postgres_catalog:    
